### ISSUE TITLE
Crash: IndexOutOfBoundsException (Crystalize Base, Animation, "tiny_potatog/animation.tongue")

### ISSUE THREAD

**Issue by nahkd123** [nahkd123/crystalize#2]
Trimmed stacktrace:

```
net.minecraft.util.crash.CrashException: Exception ticking world
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at io.github.nahkd123.crystalize.anim.Timeline.interpolate(Timeline.java:47) ~[main/:?]
	at io.github.nahkd123.crystalize.anim.TimelineGroup.interpolate(TimelineGroup.java:26) ~[main/:?]
	at io.github.nahkd123.crystalize.anim.controller.TemplatedAnimationController.animate(TemplatedAnimationController.java:95) ~[main/:?]
	at io.github.nahkd123.crystalize.fabric.model.BonePart.updateTree(BonePart.java:89) ~[main/:?]
	at io.github.nahkd123.crystalize.fabric.model.BonePart.updateTree(BonePart.java:124) ~[main/:?]
	at io.github.nahkd123.crystalize.fabric.model.BonePart.updateTree(BonePart.java:124) ~[main/:?]
	at io.github.nahkd123.crystalize.fabric.model.BonePart.updateTree(BonePart.java:124) ~[main/:?]
	at io.github.nahkd123.crystalize.fabric.model.CrystalizeElementHolder.onTick(CrystalizeElementHolder.java:111) ~[main/:?]
	... ?? more
```

The exception appears to be coming from Crystalize Base.

**Comment by nahkd123** [comment]
Error with SCALE channel
